//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 04:52:13 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.javaspringclub.com/movies-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package generate;

